### ISSUE TITLE
Init objects in service...

### ISSUE THREAD

**Issue by sirvon** [JoanZapata/android-asyncservice#11]
Let's say I have a analytic service, that's holding all my analytic provider method calls and inits...

in the @Init of the service I initialize all of the providers I'm using

#analyticService.java
```java
@Init
public void init() {
        mixpanel = MixpanelAPI.getInstance(context, BuildConfig.MIXPANEL_KEY);
        appboyUser = Appboy.getInstance(context).getCurrentUser();
        segmentAnalytics = new Analytics.Builder(context, BuildConfig.SEGMENT_KEY).build();
}
```

Now when I make a call to a method in this service having to do with let's say mixpanel...

```java
#MainActivity.java
analyticService.trackDataMixpanel()

#AnalyticService.java
public void trackDataMixpanel(){
.....
}
```

everytime I make that call all those other analytic service providers instances will intialize?
is that wrong? wasteful?

should I just have a initMixpanel() method in the analytic service?

but let's say I want to use the mixpanel instance or the appboy instance inside the analytic service...just call the initAppboy() method 

```java
trackEventsAllProviders(){
   initMixpanel()
   initAppboy()
   initSegment()
   do work.......
}

can you give me some pointers?

thanks!


```

**Comment by JoanZapata** [comment]
If you feel that your activity is slow to show up the first time, then yes, only initialize the providers when you first need it. Otherwise it's not that bad to put everything in the `init` method.
