### ISSUE TITLE
how would you cancel the current running service?

### ISSUE THREAD

**Issue by k0shk0sh** [JoanZapata/android-asyncservice#15]
i have tried almost everything to stop the current task, but it doesn't stop. is there any way to stop current running service?

**Comment by JoanZapata** [comment]
You can cancel all tasks being run on a specific `@Serial` using `BackgroundExecutor.cancelAll(<serial_name>, true);`.

**Comment by k0shk0sh** [comment]
could u please provide an example? as i find it a bit difficult, and btw, why do i need to declare all fields as static?

**Comment by JoanZapata** [comment]
Let's say you have this method in you service:

``` java
@Serial("Test")
public void getSomething(){
    // ... Long running op
}
```

Then you can cancel any currently running operation doing:

``` java
BackgroundExecutor.cancelAll("Test", true);
```

Fields must be static because the service is instantiated for each receiver, if the field isn't static you could have different value in different service.

**Comment by k0shk0sh** [comment]
thanks for your feedback, i'm definitely going to be using this library.

**Comment by k0shk0sh** [comment]
unfortunately calling  `BackgroundExecutor.cancelAll("BackupService", true);` doesn't stop the operation.  the asyncserivce is running from a Service, calling cancelAll and unregister doesn't stop the task.
