### ISSUE TITLE
Don't working with proguard

### ISSUE THREAD

**Issue by quxey** [JoanZapata/android-asyncservice#4]
Can you post your proguard rules?

I can compile project with these rules, but when i try call service.doSomething(); App crashes from nullPointerException. Everything is fine without proguard

-dontwarn com.joanzapata.android.asyncservice.**
-dontwarn com.esotericsoftware.**
-dontwarn com.squareup.javawriter.**
 -keep public class com.joanzapata.android.asyncservice.api.** {
    public protected private *;
 }

**Comment by JoanZapata** [comment]
Sure. This is what I used in my project, but I'm not really into proguard and we didn't really care about code protection so maybe it keeps too much names.

```
-dontwarn com.joanzapata.android.asyncservice.**
-keep @com.joanzapata.android.asyncservice.api.annotation.AsyncService class *
-keep class **Injector
-keepnames class **Injector
-keepnames class * {
    @com.joanzapata.android.asyncservice.api.annotation.InjectService *;
}
-keepnames class * {
    @com.joanzapata.android.asyncservice.api.annotation.OnMessage *;
}
```

**Comment by mradzinski** [comment]
I do recommend adding this ProGuard configuration to the Readme of the project for easier access and clarity.

**Comment by JoanZapata** [comment]
Done! :)
