### ISSUE TITLE
Not working with Generic Type

### ISSUE THREAD

**Issue by b22n** [JoanZapata/android-asyncservice#5]
It causes build errors when using the generic type.
ex) public abstract class ExActivity<T> extends Activity

**Comment by hitesh-buzz4health** [comment]
+1

**Comment by hitesh-buzz4health** [comment]
Returning parameterized is not allowed e.g. List<User> although the documentation shows it as an example.

**Comment by JoanZapata** [comment]
Yes sorry this is not supported anymore, because generics are not anymore present at runtime. 
I'll have to update the docs. Please use a wrapper class instead.

**Comment by hitesh-buzz4health** [comment]
Thanks for the reply. I did use a wrapper as a workaround, but it seems to have issues while caching(specifically serialization/deserialization). A working example of a function in AppService returning a wrapper of list would be really helpful.

**Comment by JoanZapata** [comment]
What kind of issues?

**Comment by hitesh-buzz4health** [comment]
The following error message when trying to cache a wrapper object. This exception eventually causes to delete the keys e,g. AsyncCache::get() :


" Maybe you tried to retrieve an array using this method ? please use getArray instead Class cannot be created (missing no-arg constructor):"

**Comment by JoanZapata** [comment]
This is not related to generic types, could you open another issue about it? Also, the error message says `Class cannot be created (missing no-arg constructor)`, are you sure you're not missing a no-arg constructor for the objects you're trying to cache?

**Comment by JoanZapata** [comment]
Wiki has been updated.
