### ISSUE TITLE
Example use case...

### ISSUE THREAD

**Issue by sirvon** [JoanZapata/android-asyncservice#8]
This is a useful lib, lil tricky in implementing some possiblities nevertheless...

so, let's say I have tons of methods like this:

```java
Analytics analytics = new Analytics.Builder(mContext, BuildConfig.SEGMENT_KEY).build();
        Analytics.setSingletonInstance(analytics);

 TypefaceHelper.initialize(this);

Foreground.init(this);

 Indicative.launch(getApplicationContext(), BuildConfig.INDICATIVE_API_KEY);
        final TwitterAuthConfig authConfig = new TwitterAuthConfig(BuildConfig.TWITTER_CONSUMER_KEY,
                BuildConfig.TWITTER_CONSUMER_SECRET);

Fabric.with(this, new Crashlytics(), new Twitter(authConfig),new MoPub());
```

 that need initializing in the Application class for use throughout the app.

I want to speed up the app's startup so i want to async off load all the initializations i'm doing in the App class.

How would I go about doing that using Services and then bring the objects back into the Application class to be available throughout the app?

thanks for your work!

**Comment by JoanZapata** [comment]
I don't think this use case is related to this lib. Doing initialization in a background process is a good idea, and I don't see why this would not be possible using AsyncService. But then you'll probably have your activities requesting some of them before they're initialized. I think RxJava would be good at this, using hot observables (most probably BehaviorSubject) at the application level, and letting activities subscribe on it to use them as soon as their ready. If that's okay I'm closing this issue now.
