### ISSUE TITLE
Issue with Twitter Fabric Library

### ISSUE THREAD

**Issue by ipragmatechadmin** [JoanZapata/android-asyncservice#9]
We are trying to use the twitter's fabric library but looks like injector are not generating. Looks like there are conflicts.

Could not find class 'XXX.LoginServiceImpl', referenced from method XXX.LoginActivityInjector.inject
05-21 16:01:06.689  22161-22161/XXXX E/AndroidRuntime﹕ FATAL EXCEPTION: main

**Comment by JoanZapata** [comment]
It seems weird that `LoginActivityInjector` is created but not `LoginServiceImpl`, but anyway, are you sure this is related to Fabric?

**Comment by ipragmatechadmin** [comment]
Thx for quick reply. Yes, Its ServiceImpl which is not being generated. Yes, I am sure that whenever I initialise Fabric Library and it asyncService stop working. If you want then I can send you source code for the demo app based on this example http://www.ipragmatech.com/android-asyncservice-robust-and-flexible-mobile-app ?

**Comment by JoanZapata** [comment]
I've never used Fabric but they don't seem to use annotation processing, that should not cause a conflict. 
How and where do you initialize it?

**Comment by ipragmatechadmin** [comment]
Well, I have tried initialising Async service both in activity and custom Application like this:

TwitterAuthConfig authConfig = new TwitterAuthConfig(TWITTER_KEY, TWITTER_SECRET);
 Fabric.with(this, new Twitter(authConfig));
 AsyncService.inject(this);

If I remove the initialisation of Fabric then AsyncService works fine.

If you don't mind then I have one more question related to Cache,  What is the best way to cache the pagination list? At the moment, I am passing the full object in the method but as per the documentation, this won't work for the different pages. Should I add additional parameter in my method ?: 

 @CacheThenCall(validity = 10000)
  public UserResponse getUserAsyncWithCache(LoginRequest request)

**Comment by JoanZapata** [comment]
I'm sorry but I have no idea how `Fabric.with(...)` can prevent the generation of your app... Is there any error or warning before during the build?

About your second question, if you want to cache pages you can add it to the cache key, something like this:
```java
@CacheThenCall(validity = 10000, key="getUserAsyncWithCache({page})")
public UserResponse getUserAsyncWithCache(LoginRequest request, int page)
```

If pagination information is already present in `LoginRequest` you can also access it like this:
```java
@CacheThenCall(validity = 10000, key="getUserAsyncWithCache({request.page})")
public UserResponse getUserAsyncWithCache(LoginRequest request)
```

**Comment by ipragmatechadmin** [comment]
Thx a lot for your help, I figured out the problem it seems. It may be due to numbers of third party libraries that I am using.Let me find out exact issue and I shall let you know if it's related asyncService or something also.

Thx for sending me the best way to use the pagination and it should help us :-)

**Comment by ipragmatechadmin** [comment]
Yes, it was issue related to the app size. I turned on the proguard and app is working fine now. 

I really appreciate your support and if you want then we would be happy to share the example of RestTemplate using AsyncService with you.
